### ISSUE TITLE
Improve Responsiveness of UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1105]
There are a number of pages, where the design is not final. There is no point in getting into too much detail on those pages. However there are areas that are pretty clear already, e.g. top bar and footer. Please add areas here and create issues for each one.

Improve Responsiveness of:
* [x] Top bar menu https://github.com/fossasia/open-event-orga-server/issues/1081
* [x] Footer design https://github.com/fossasia/open-event-orga-server/issues/764
* [x] Wizard https://github.com/fossasia/open-event-orga-server/issues/868
* [x] Tabs https://github.com/fossasia/open-event-orga-server/issues/1106
