### ISSUE TITLE
Propose Internationalization Flow

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2046]
How can we implement internationalization? Things to take into account:
- [x] Translate UI and make it country specific, e.g. offer Canada (EN) and Canada (FR)
- [x] Multilanguage Version of Pages https://open-event-dev.herokuapp.com/admin/content/
- [x] Names of locations e.g. cities have different names in different languages
- [x] Propose workflow for volunteers to translate system

![screenshot from 2016-08-04 09 32 59](https://cloud.githubusercontent.com/assets/1583873/17393911/b706070a-5a26-11e6-972e-40d3ab1d8d3d.png)

**Comment by rafalkowalski** [comment]
I think that Flask Babel https://pythonhosted.org/Flask-Babel/ library will be enough, to translate UI. Then we need to define a page where volonteers can easily edit page content.

**Comment by aditya1702** [comment]
@mariobehling Yes we can implement it using Flask Babel

**Comment by mariobehling** [comment]
> Then we need to define a page where volonteers can easily edit page content.

How? Where? I do not see this kind of option in Babel. As far as I can see a solution to edit pot/po files is needed.

**Comment by rafalkowalski** [comment]
So My idea is to create tab in admin panel where volunteers can choose language then have a possibility to edit phrases via simple html form.

**Comment by mariobehling** [comment]
@rafalkowalski We do not really want to handle volunteers directly on the system. It would be better if we could upload po/pot files (whatever is needed) into the system directly. So it would be good to:
* [ ] a) to have the ability to download the original po/pot as a sample for translation (and that can be used in translation applications like rosetta
* [ ] b) have the ability to upload po/pot files for new/updated languages directly into the system
* [ ] c) have a folder where po/pot's can be added in the repo

**Comment by mariobehling** [comment]
As we are getting closer to the release and still do not have an internationalization implementation this is a blocker now.

**Comment by SaptakS** [comment]
@mariobehling I think we can use [this](http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xiv-i18n-and-l10n)

**Comment by mariobehling** [comment]
@SaptakS That is the same that was suggested in this thread already, isn't it? So, if everyone is suggesting this. Let's go with it.

**Comment by sainiak009** [comment]
This is how I propose to implement it : 

- I will define a "Languages" dictionary in config.py where all the available languages will be listed.

- A localeselector function needs to be defined which will return best match from Accept-Languages header of browser or user can select his language from available languages.

- All text in views and templates which will need translation needs to be marked.

- A .pot file will be generate in root directory which will contain all marked text.

- A directory needs to be created alongside "templates" directory which will contain .po and .mo files.

- A tab named "translations" will be added under contents tab of admin panel from where .po files can be uploaded and downloaded.


- As .po files needs to be compiled to use in application, So as @niranjan94 suggested : 
We could do the initial compile every time the server is started. And when any changes are made to the translation file (by uploading the .po file) we could run the command as a part of the upload process. (i.e) the file gets uploaded, and then compiled.

@mariobehling @niranjan94 : Let me know if I can go ahead with it.

**Comment by niranjan94** [comment]
@mariobehling the above implementation sounds good. What do you think ?

**Comment by mariobehling** [comment]
@niranjan94 @sainiak009 Sound good. Let's go for it!

**Comment by sainiak009** [comment]
@niranjan94 @mariobehling Is there anything left for closing this issue ?

**Comment by niranjan94** [comment]
@sainiak009 I think this issue can be closed. Anything else, could be put in a new issue :) ... You did a wonderful job with this !! :D ... Thanks ... :)

**Comment by mariobehling** [comment]
@sainiak009 Great job! Thank you. Let's get the internationalization rolling now. Cheers.
