### ISSUE TITLE
Add missing features to Ticketing System

### ISSUE THREAD

**Issue by shivamMg** [fossasia/open-event-orga-server#2082]
Extended from: https://github.com/fossasia/open-event-orga-server/issues/1112

* [x] Toggle ticket description: 
        
Show/Hide Ticket description on the public Event page.

![screenshot from 2016-08-07 19 09 17](https://cloud.githubusercontent.com/assets/7882752/17462677/95501f34-5cd2-11e6-89de-850c21be5bce.png)

* [x] Support for Ticket Tags to group them. Example from Eventbrite:

![screenshot from 2016-08-07 19 02 29](https://cloud.githubusercontent.com/assets/7882752/17462651/81ada998-5cd1-11e6-8116-a0f4e39c4751.png)

* [x] Option to make tickets invisible (stop their sale). https://github.com/fossasia/open-event-orga-server/issues/2044#issuecomment-237481910

* [ ] <del>Option for selecting Sales channel. Example from Eventbrite:</del> Sales channel is not implemented on per Ticket basis, rather it is done per Event basis.

![screenshot from 2016-08-07 19 04 04](https://cloud.githubusercontent.com/assets/7882752/17462655/cfd7880a-5cd1-11e6-8723-8c65d836ead7.png)

**Comment by mariobehling** [comment]
"Support for Ticket Tags to group them" What does it mean? Please provide an example and screenshot.
