### ISSUE TITLE
Implement import support for other formats

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2185]
There are a number of formats of events that are similar but still different. How can we import more formats?

Please
- [x] Find other formats
- [ ] Implement import support for https://github.com/frab
  - [x] Pentabarf XML, example https://archive.fosdem.org/2016/schedule/xml (#2585)
  - [x] iCal, example https://archive.fosdem.org/2016/schedule/ical (#2635)
  - [ ] xCal, example https://archive.fosdem.org/2016/schedule/xcal

**Comment by Jatinbalodhi96** [comment]
is xcal format import finished? or someone working on this?

**Comment by aviaryan** [comment]
@Jatinbalodhi96 No, it's not implemented yet. You can go ahead and send a PR 😄

**Comment by mariobehling** [comment]
Let's review import and export features once we switch to the next version and open relevant issues then. Closing it therefore.
