### ISSUE TITLE
Implement discount code for events and marketers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2324]
As we need to get marketers support to get the event system used, we need a way to identify which event organizer comes through which marketer. A way to achieve this is through discount codes.

To do this we need a way to create discount codes and link them to specific marketers accounts. So, for example a marketer gives out a discount code "X20482TOP" and that discount code gets organizers off 10% for an event over three months. Then in the monthly report the event organizer needs to get 10% off from the money he needs to pay.

In the admin sales overview we should also have a column "Marketer" to show all events with discount codes of a specific marketer. Based on the sales we can then share the income with a marketer.

Features we need are:

* [x] Implement Role "Marketer" as System role https://github.com/fossasia/open-event-orga-server/issues/2453
* [x] Possibility to create event discounts with percentage, number of times the discount voucher is valid and user account the voucher is linked to
* [x] Show of discounts in column in sales and show of linked marketer
* [x] Calculate discount in sales monthly
* [x] Implement Sales overview for events of marketers (where and how would that be best?)
* [x] In admin tab "Sales" show subtab sales "By Marketer" https://github.com/fossasia/open-event-orga-server/issues/2452
* [x] In admin tab "Sales" show subtab sales "By Discount Code" https://github.com/fossasia/open-event-orga-server/issues/2452

**Comment by niranjan94** [comment]
@mariobehling the discount vouchers for the **marketers** can be created by **sales admin** and the **administrator**. Correct ?

**Comment by mariobehling** [comment]
> 1. the discount vouchers for the **marketers** can be created by **sales admin** and the **administrator**. Correct ? 

Yes, correct.

2. Where would the new event organizer _enter_ the discount code that he/she has been given by the marketer ??

> It should probably go into a field "discount code" in the ticketing area of wizard step 1.

**Comment by niranjan94** [comment]
> Implement Sales overview for events of marketers (where and how would that be best?)

@mariobehling In the admin sales page, we could have a tab named **promoted events** and display only the events that have a discount code applied. The display format can be the same as that of the **By events** with an additional column with the discount code applied and marketer name.

**Comment by mariobehling** [comment]
@niranjan94 Yes, good idea. Please proceed.

There is an additional requirement - specific marketer should only see the events with codes assigned to him/herself. Can we do that?

**Comment by niranjan94** [comment]
@mariobehling yes. that can be done.
