### ISSUE TITLE
Implement support for Export of other formats

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2422]
There are a number of formats of events that are similar but still different. How can we export more formats?

Please
* [x] Find other formats
* [x] Implement import support for https://github.com/frab
  * [x] Pentabarf XML, example https://archive.fosdem.org/2016/schedule/xml (#2498)
  * [x] iCal, example https://archive.fosdem.org/2016/schedule/ical (#2499)
  * [x] xCal, example https://archive.fosdem.org/2016/schedule/xcal (#2500)

Related to: https://github.com/fossasia/open-event-orga-server/issues/2185

**Comment by SaptakS** [comment]
@mariobehling we can already export it in iCal format once the scheduling of the session is done for a particular event. I don't think we can export in a calendar format until the sessions are scheduled. Please share your views.

Meanwhile I will check out the other formats.

**Comment by mariobehling** [comment]
@SaptakS Yes, correct.
