### ISSUE TITLE
Set up System on Google Cloud and configure automatic deployments

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2495]
Kubernetes enables applications to scale up or down based on the needs. Please set up eventyay on Google cloud. 

Discussed set up:
- deploy DB on one system
- deploy other parts on separate container(s)

Other:
- Document how to ensure updates (continues integration/continuous deployment)

**Comment by niranjan94** [comment]
**TODO:**
- [ ] Persistent storage disk for PostgreSQL & Redis
- [ ] Fix `404` error on deployment by properly setting SERVER_NAME during deployment 
- [ ] Continuous deployment on each GitHub push (like heroku)

**Comment by mariobehling** [comment]
>  Continuous deployment on each GitHub push (like heroku)

I guess, we should be adding another branch "production" after an initial test period.

**Comment by niranjan94** [comment]
@mariobehling correct. And that branch should also have tagged releases.
