### ISSUE TITLE
Add "Action" dropdown menu to the last column on the specific event ticket dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2996]
Add "Action" dropdown menu to the last column on the specific event ticket dashboard with the following action items:

* [x] Mark as Cancel -> Send user to cancel form https://github.com/fossasia/open-event-orga-server/issues/2997
* [x] Resend Confirmation Email -> Directing user to Email resend form https://github.com/fossasia/open-event-orga-server/issues/2998
* [ ] Edit Order Info -> Directing user to ticket details and allowing edits

![screenshot from 2017-01-19 23-03-50](https://cloud.githubusercontent.com/assets/1583873/22127762/af560dba-de9d-11e6-823b-9a2715052ccc.png)

**Comment by niranjan94** [comment]
Linked to related API issue. 
`frontend` tag added and issue will be re-created on frontend repo.
