### ISSUE TITLE
Implement Event Stages

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#306]
- [x] Stage 1 Create Event #324
- [x] Stage 2 Call for Speakers #325 
- [x] Stage 3 Create Schedule #326 
- [x] Stage 4 Schedule Published #619 
- [x] Stage 5 Event #620
- [x] Stage 6 After Event #621

**Comment by mariobehling** [comment]
Closing it: We need to refine the system now and fix all kinds of bugs. Please help with bugs.
