### ISSUE TITLE
Event Stage 1 name: Event Details

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#324]
Project Issue #306 Event Stage 1 name: Event Details
EVENT VIEW: /admin/events/[eventID]/

Implement Wizard for Event Creation
* [x] Step 1: Event Details https://github.com/fossasia/open-event-orga-server/issues/634
* [x] Step 2: Create Event Wizard Step 2: Sponsors #697
* [x] Step 3: Session Types #635, Tracks & Rooms https://github.com/fossasia/open-event-orga-server/issues/636
* [x] Step 4: Call for Speakers https://github.com/fossasia/open-event-orga-server/issues/637
* [x] Step 5: Speaker Submissions (Forms) (session submission and profile submission) https://github.com/fossasia/open-event-orga-server/issues/638

**Comment by mariobehling** [comment]
Let's also get the UI right. Currently it is difficult to reduce the width and the UI does not display well on small and mobile screens. Please fix:
* [ ] top line of 1-2-3-4 should scale smaller than currently possible. Also ensure distance between all points is even
* [ ] in smaller width the is a scroll bar inside the window that comes up (see below). Ensure that the sites adapts to different sizes without internal scroll bar.
![screenshot from 2016-06-05 14 46 35](https://cloud.githubusercontent.com/assets/1583873/15805495/d0e36600-2b2c-11e6-83a5-611001516777.png)

Please take more inspiration from existing services like Eventbrite and Eventnook. 

![screenshot-www eventbrite com 2016-06-05 10-26-54](https://cloud.githubusercontent.com/assets/1583873/15805505/24382520-2b2d-11e6-8c1d-4b427e29d4ab.jpg)

**Comment by SaptakS** [comment]
@mariobehling @rafalkowalski This is the prototype I have created:-

Step - 1: Basic Details
![screenshot from 2016-06-09 01 56 51](https://cloud.githubusercontent.com/assets/9530293/15909789/96b18564-2de5-11e6-8d18-724d54c068e7.png)

Step - 2: Session Types
![screenshot from 2016-06-09 01 56 59](https://cloud.githubusercontent.com/assets/9530293/15909790/96b485a2-2de5-11e6-8276-82d72c74b69e.png)

Step - 3: Tracks & Rooms
![screenshot from 2016-06-09 01 57 03](https://cloud.githubusercontent.com/assets/9530293/15909791/96b6130e-2de5-11e6-8cd4-063559722691.png)

Step-4: Call for Speakers Announcement
![screenshot from 2016-06-09 01 57 09](https://cloud.githubusercontent.com/assets/9530293/15909793/96b73a04-2de5-11e6-9529-0ec4cb91d86a.png)

What do you think?

**Comment by rafalkowalski** [comment]
@mariobehling @SaptakS @niranjan94 can we close this?

**Comment by niranjan94** [comment]
@rafalkowalski yes. We can :smile:
