### ISSUE TITLE
Event Stage 2 name: Call for Speakers

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#325]
#306 Wizard step 2 name: Call for Speakers
EVENT VIEW: /admin/events/[eventID]/
EVENTS DETAILS (like in step 1)
Event and Call for Speakers Published
* [x] Publish Call for Speakers and show CfS on a dedicated page (Offer date setting to open and close CfS automatically depending on date chosen)
* [ ] Offer organizer to sent out Announcement Email (#1237)
* ~~Offer organizer to sent out tweet~~ (#1238) (Let's move this feature to a later milestone)
* ~~Offer organizer to publish updates on Facebook Event or Page~~ (#1239) (Move it to later milestone.)

After Activation
* [x] BUTTONS : INVITE, ACCEPT/REJECTED (Only Visible in Event Call for Speakers state)
- [x] Show Sessions (Only Visible in Event Call for Speakers)
- [x] Show Statistic: x session submitted / x days left(Only Visible in Event Call for Speakers state)

**Comment by SaptakS** [comment]
- [ ] Add/update closing date (https://github.com/fossasia/open-event-orga-server/issues/446)
- [ ] Invite users by email_id (https://github.com/fossasia/open-event-orga-server/issues/445)
- [ ] Users get Notified on login about the invitation
- [ ] Users submit papers
- [ ] Accept/reject papers
