### ISSUE TITLE
Implementation of the Scheduler UI

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#349]
The Scheduler would allow the organizers to graphically schedule/manage the sessions in their conference/event. The proposed features for the Scheduler are:

1. Drag-and-drop sessions into tracks on a timeline.
1. Change the timings of the sessions by resizing the sessions' element on the timeline.
1. Create new tracks.
1. Switch between timelines of the different days of the event.
1. Print the timeline or convert it into a PDF file.
1. Export the schedule in different formats such as iCalendar.

_@niranjan94 and @SaptakS will be primarily working on this._

> The scheduler will be part of the wizard as outlined in #326.

**The tasks that are to be completed for this are:**
- [x] Drag-and-drop interface to add session blocks into a timeline (#365)
- [x] Resize sessions to change time (#365)
- [x] load live data from the server using the API (#404)
- [x] Handle session clashes within a track properly (#424)
- [x] _Add Track button_ that opens up a modal to add a track. (#411)
- [x] Search option for unscheduled sessions (#449)
- [x] Option to export timeline/calendar as iCal (#514)
- [x] Option to Export timeline as PNG (#512)
- [x] Save each session change/update using the API (#412)
- [x] Option to edit the session from the timeline (#513)

**Comment by niranjan94** [comment]
@mariobehling @leto @juslee I have been working on a prototype for the Scheduling UI. 

I built a basic one with:
- Drag and drop sessions into tracks
- Graphically resize sessions to change timings.

It can be previewed at https://oes-testbed.codezero.xyz/scheduling/ .

It's still a primitive interface. 
Any suggestions are welcome.

**Comment by niranjan94** [comment]
As of now, it's hosted as a static site (since it's just a prototype).

If you guys are fine with this idea, I'll start implementing it into the Open Event Server UI and continue to build upon it.

**Comment by SaptakS** [comment]
I was thinking that along with drag & drop feature we can also create a new event directly by clicking or dragging over a time period. Also, if a specific time is mentioned while creating the event, it should be automatically there on the calendar.

**Comment by rafalkowalski** [comment]
@niranjan94 I think it's exactly what we need. 
@SaptakS great idea

**Comment by aayusharora** [comment]
@niranjan94 , in this schedule tabular UI , genetellela will become unresponsive . I have checked it on my mobile . Please check if you have used col-xs

**Comment by niranjan94** [comment]
@SaptakS That's a wonderful  idea... I'll implement what has been done till now into the Server UI today . Then you can add that into it. Fine? 

@aayusharora yea... I think I used xs. Will fix it. But I don't think the scheduler UI would be easy to use on a small screen.

**Comment by aayusharora** [comment]
@niranjan94 , we have to go for something simpler for mobile then.

**Comment by SaptakS** [comment]
I agree with @niranjan94 . Scheduler UI is something I don't thing will be used from mobile. But we will still need to make some alternative for the mobile as well..
