### ISSUE TITLE
Create Session Wizard

### ISSUE THREAD

**Issue by SaptakS** [fossasia/open-event-orga-server#602]
To add Speaker details and add/invite other speakers for a session, I guess it is best to have a session Wizard.

The wizard will have 3 steps:-
- [x] Add session details https://github.com/fossasia/open-event-orga-server/issues/631
- [x] Add speaker/self details https://github.com/fossasia/open-event-orga-server/issues/632
- [x] Invite other speakers for session #792 

At the beginning, the session will be added with a "pending" state to the DB. The organizer can either "accept" or "reject" the session.

The Speaker can also edit the session and Invite Speakers later.

This is a rough design workflow
![screenshot from 2016-06-07 12 09 09](https://cloud.githubusercontent.com/assets/9530293/15848149/b7c57a50-2ca8-11e6-92e4-7459f830d475.png)

@rafalkowalski @aditya1702 @mariobehling @juslee What do you think?

**Comment by mariobehling** [comment]
@SaptakS Looks good. Speakers can of course also just "answer the call for papers" and propose a session without getting an invite. Apart from that organizers should be able to add sessions as well. Do you have a screenshot how things should look like?

**Comment by SaptakS** [comment]
@mariobehling It isn't ready yet... I will provide a screenshot as soon as I get it done. Thanks. :)

**Comment by SaptakS** [comment]
@mariobehling 
![screenshot from 2016-06-08 00 20 24](https://cloud.githubusercontent.com/assets/9530293/15870966/edd3f7a4-2d0f-11e6-8150-a8a457d4ea04.png)
![screenshot from 2016-06-08 00 20 29](https://cloud.githubusercontent.com/assets/9530293/15870967/edd6786c-2d0f-11e6-862e-c12f7fcb330c.png)
![screenshot from 2016-06-08 00 20 33](https://cloud.githubusercontent.com/assets/9530293/15870968/ede14f30-2d0f-11e6-9eec-c8873e3ef36d.png)

**Comment by mariobehling** [comment]
I am not sure, if the speaker details should just be kept in the profile. Did you have a look at the speakers form of the last FOSSASIA?

**Comment by mariobehling** [comment]
Start and End time in first step does not make sense and order does not make sense entirely. Let's create sub issues for this. https://github.com/fossasia/open-event-orga-server/issues/631

**Comment by SaptakS** [comment]
@mariobehling what order do you suggest? And I don't understand what you mean to say by
" if the speaker details should just be kept in the profile "

**Comment by mariobehling** [comment]
Let's follow up in #631 and #632 for specific questions later. 

No need to think about speaker profile atm. Just keep it simple first. We can follow up on this later.

**Comment by SaptakS** [comment]
@mariobehling can we close #631 and #632 ?

**Comment by mariobehling** [comment]
#631 is incomplete. i have not gotten to test the invite speakers function. Did you? Does it work?

**Comment by SaptakS** [comment]
Invite speakers isn't working. I will create an issue and implement that feature.
