### ISSUE TITLE
Implement the Event API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#612]
* [x] Define Event API with fields and methods https://github.com/fossasia/open-event-orga-server/issues/598
* [x] Implement Event API in Orga Server and ensure all operations are be possible using API
* [x] To POST, PUT, DELETE methods check permissions
* [x] Document all API fields, methods and access in API.md
