### ISSUE TITLE
Implement Session API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#613]
* [x] Define Session API with fields and methods
* [x] Implement Session API in Orga Server and ensure all operations are be possible using API
* [x] To POST, PUT, DELETE methods check permissions
* [x] Document all API fields, methods and access in API.md
