### ISSUE TITLE
Implement Track API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#614]
* [x] Define Track API with fields and methods
* [x] Implement Track API in Orga Server and ensure all operations are be possible using API
* [x] To POST, PUT, DELETE methods check permissions
* [x] Document all API fields, methods and access in API.md
