### ISSUE TITLE
Implement Microlocation API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#616]
* [x] Define Microlocation API with fields and methods
* [x] Implement Microlocation API in Orga Server and ensure all operations are be possible using API
* [x] To POST, PUT, DELETE methods check permissions
* [x] Document all API fields, methods and access in API.md
