### ISSUE TITLE
Implement Profile API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#617]
* [x] Define Profile API with fields and methods
* [x] Implement Profile API in Orga Server and ensure all operations are be possible using API
* [x] To POST, PUT, DELETE methods check permissions
* [ ] Some Get methods also might need permissions
* [x] Document all API fields, methods and access in API.md

**Comment by aviaryan** [comment]
Hi @mariobehling 
I have doubts with this issue. 
First of all, Profile API means User API right. So do we need to have DELETE API (to delete a user account) ? In other words, will it be possible for a user to delete their account ?
Thanks

**Comment by mariobehling** [comment]
@aviaryan Please discuss the details with @rafalkowalski

**Comment by aviaryan** [comment]
@rafalkowalski @shivamMg 
This is what I have thought so far.. 

1. POST
To keep it simple, post email and password to `/users` to create a user.

2. GET
GET on `/users` returns all users. 
Apart from that, GET on `/users/events/<id>` returns all users part of event with id <id>
GET on `/users/<id>` returns full user profile

3. PUT
PUT on `/users/<id>` is to update a profile

4. DELETE
DELETE on `/users/<id>` deletes a profile.

Apart from that, there will be endpoints for managing roles but I think they come under Event API. We can add it after permission and access system is set up.

**Comment by mariobehling** [comment]
In order to make it easier for us to understand please list all fields and make a sample JSON that would be exported using this API.

**Comment by aviaryan** [comment]
@mariobehling 
Here is the sample output 
```json
{
    "id": 1,
    "email": "email@gmail.com",
    "user_detail": {
        "fullname": "John Doe",
        "details": "bio",
        "avatar": "http://link.to/avatar",
        "contact": "+91823234433",
        "facebook": "http://fb.com/link",
        "twitter": "http://twitter.com/link"
    }
}
```

This is consistent with how user is stored internally but if needed I can take out that `user_detail` envelope.

**Comment by mariobehling** [comment]
What about the picture, github etc.?

How do we restrict access to certain fields? E.g. we want people to be able to access certain data like link to the speakers website, but we dont want to make the phone number public.

**Comment by aviaryan** [comment]
> What about the picture, github etc.?

picture = avatar in the above json .. Link to user's photo

github, linkedin, website etc have been defined in speaker's model and not in user's. But now that I think of it, it doesn't make sense to have it in speaker's model as a user could be speaker in many events. It makes no sense to copy same values multiple times. This is the current list of fields in a speaker model.

name, photo, biography, email, web, twitter, facebook, github, linkedin, organisation, position, country, event_id

I think we don't need name, photo, bio, email, twitter, facebook in speaker's fields as they are already in user model.
Also github, linkedin, country (possibly organisation and position) can be moved to user model.
Therefore speaker model should only store a link between user and event and link to sessions they take. (But of courese Speaker API will show the full user data)

@mariobehling @rafalkowalski @niranjan94 @shivamMg  What do you think ? 

> How do we restrict access to certain fields? E.g. we want people to be able to access certain data like link to the speakers website, but we dont want to make the phone number public.

Supposing that only track organizers, event organizers and the speaker himself can see the phone number, we can do it once permissions is implemented. It will be done by changing the model that the data is marshalled with a/c the access level. This can be easily done in flask-restplus framework .

**Comment by mariobehling** [comment]
@aviaryan There could be different kind of events, where a speaker wants to provide a different photo and bio. Also, we dont want to change former event data with updated information possibly. So, keeping some of the data separate for each event could make sense. Maybe we can offer the option "copy data from your profile to this event".

**Comment by aviaryan** [comment]
> Maybe we can offer the option "copy data from your profile to this event".

:+1:
I will do this tomorrow.

**Comment by aviaryan** [comment]
working on this now.
