### ISSUE TITLE
Implement Speakers API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#618]
* [x] Define Speakers API with fields and methods
* [x] Implement Speakers API in Orga Server and ensure all operations are be possible using API
* [x] To POST, PUT, DELETE methods check permissions
* [x] Document all API fields, methods and access in API.md
