### ISSUE TITLE
Event Stage 4 name: Schedule Published

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#619]
Project Issue: https://github.com/fossasia/open-event-orga-server/issues/326 Wizard step 4 name:: Schedule Published [Scheduling]
* [x] Implement sent out email to Speakers (see how Eventbrite does it, need to offer Email capabilities)
* [x] Publish Schedule functionality depending on date chosen (similar to CfS, but without an unpublishing date)
* [x] Implement that each generated schedule version has a "published date"
* [x] Enable organizers and track responsibles to add more data e.g. video/audio link to live media is added, slides are added; 
* [ ] Connect to Web App Generator: Schedule is generated on link automatically and offered as a Zip (Event App Generator), preferably as a microservice
* [ ] Connect to Android App Generator offered as Android App (Event App Generator) / preferably as a microservice

**Comment by niranjan94** [comment]
@mariobehling 
> Publish Schedule functionality depending on date chosen 
Publish to where ?

**Comment by mariobehling** [comment]
@niranjan94 The schedule is only public, when it is published.
