### ISSUE TITLE
Implement URL structure and architecture as outlined and document it

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#622]
## USER/ADMIN UI/ORGANIZER

* [x] HOME Open-Event main page https://github.com/fossasia/open-event-orga-server/issues/650
    - `/`
    - Create event (big button)
    - Upcoming events (boxes of events)
    - Call for Speakers (boxes of events)
* [x] PROFILE https://github.com/fossasia/open-event-orga-server/issues/688
    - `/myprofile`
    - Add feature to let user add and edit basic profile info
* [x] CREATE EVENT
    -  `/create`
    - Show page for event flow creation
* [x] MANAGE EVENTS DASHBOARD https://github.com/fossasia/open-event-orga-server/issues/686
    - `/events/`
    - Shows a simple list of all events or an organizer or if empty a button "create event"
* [x] SPECIFIC EVENT DASHBOARD
    -  `/events/ID/`
    - It shows an event dashboard with info how many proposals there are, how many speakers are 
accepted and which countries they are from
    - Propose and implement interesting widgets for the specific event dashboard (Get inspiration from the Eventnook dashboard)
    - show the stage and dates of an event, e.g. when event it will be in call for papers state
* [x] EDIT EVENT DETAILS
    - `/events/ID/edit`
    - Show Wizard flow
* [x] EDIT EVENT SPEAKERS 
    - `/events/ID/speakers/`
    - Implement show speakers list of event
* [x] EDIT EVENT SPONSORS  
    - `/events/ID/sponsors/`
    - Implement features to edit sponsors, add sponsorship levels, links and upload images and description
* [x] SCHEDULE TRACKS, ROOMS, TIMES OF EVENT
    * `/events/ID/schedule/`
    * is the public page where track organizers can drag and drop sessions in a calendar
* [x] ASSIGN EVENT ROLES
    - `/events/ID/roles/`
    - shows events roles
    - organizers can add/promote users to specific roles and invite new users to specific 'organizational' roles, e.g. ORGANIZER, CO-ORGANIZER, TRACK-ORGANIZER, MODERATOR

## SPEAKER AND/OR ORGANIZER

* [x] SPEAKER OR ORGANIZER CREATES NEW SESSIONS
    - `/events/ID/sessions/create`
    - show basic form (Session type, title, description)
    - some form elements should be optional
    - admin should be able to add more form elements (eventbrite offers something similar for attendees that register)
    - form is also dependent on tracks defined by organizer (in "Create Event")
* [x] PROPOSALS AND SESSIONS FOR ADMINS
    - `/events/ID/sessions/edit`
    - shows all sessions that have been submitted for a specific event
* [x] PROPOSALS AND SESSIONS FOR SPEAKERS
    - Relevant URLs: 
    - `/events/mysessions` - shows all sessions the user/speaker has submitted to all "his/her" events https://github.com/fossasia/open-event-orga-server/issues/703
    - `/events/mysessions/ID` - shows the specific session/sessions that the user has submitted to a specific event #705
    - Users can see on the status of the session proposal pending/rejected, accepted

## ANONYMOUS USER

* [x] SEE EVENT & SCHEDULE (#782)
    * `/e/ID/` is the public page that holds the main information of an event (Maing menu with all event links, Tag Line, Event Description, Date, Time, Newsletter, Contact, Social Media, Twitter Timeline Embed, Location with Map)
    * `/events/ID/cfs` is the public page that holds the Call for Speakers (with a register button)
    * `/e/ID/#speakers` is the section on the event page that shows all accepted speakers of an event
    * `/e/ID/#sponsors` is the section on the event page that shows all sponsors and partners of an event
    * `/e/ID/#organizers` is the section on the event page page that shows all organizers of an event
    * `/e/ID/session` is the section on the event page page that shows all sessions of an event
    * `/e/ID/coc` is the public page that shows a code of conduct if available
    * `/e/ID/schedule` is the public page where everyone can see the schedule of an event. It gets published when an organizer decides to make it public. Event unfinished (work-in-progress) schedules can be put online. Whenever the organizes publishes it, it gets generated. The event published here will be generated by the Webapp Generator.

**Comment by niranjan94** [comment]
@mariobehling this issue can be closed now ?
