### ISSUE TITLE
Session Wizard Step 1: Add Session Details

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#631]
Wizard Parent Issue: https://github.com/fossasia/open-event-orga-server/issues/602
![screenshot from 2016-06-08 00 20 24](https://cloud.githubusercontent.com/assets/9530293/15870966/edd3f7a4-2d0f-11e6-8150-a8a457d4ea04.png)

The session details need to be in a logic order and reflect the idea for the event. Some events require less information, some more. 

* [x] Prerequisite is https://github.com/fossasia/open-event-orga-server/issues/638 The organizer therefore needs to be able to edit the session form for each event.
* [x] Prerequisite is https://github.com/fossasia/open-event-orga-server/issues/638 The event organizer can choose which form elements are required.

The standard form for sessions should include:
* [x] Title
* [x] Subtitle
* [x] Short Abstract
* [x] Long Abstract
* [x] Session Type (this choice depends on the session type defined by organizers, e.g. workshop, talk etc. https://github.com/fossasia/open-event-orga-server/issues/635)
* [x] Track (this choice depends on the tracks defined by organizers https://github.com/fossasia/open-event-orga-server/issues/636)
* [x] Possibility to upload slides
* [x] Ability to add multiple links with + button and choose type (e.g. Project Website, Twitter, Facebook, Github etc.)
* [x] Other Comments for Organizers (will not be shown to public)

Other
* [x] Please take out description of menu points. It is redundant, e.g. "details about sessions" etc.

**Comment by SaptakS** [comment]
Menu point description removed https://github.com/fossasia/open-event-orga-server/pull/667

**Comment by mariobehling** [comment]
Please implement all fields in the list of this issue and follow the sorting order of the sort order of the list.

**Comment by SaptakS** [comment]
@mariobehling ohk. Will do it.

**Comment by SaptakS** [comment]
> Ability to add multiple links with + button and choose type (e.g. Project Website, Twitter, Facebook, Github etc.)

@mariobehling what exactly do you mean by these? Will this be available by default or should this be added from custom form as well?

**Comment by mariobehling** [comment]
@SaptakS We already implemented this option in step 5 of the Create Event Wizard. Just ensure anything that is marked as "Include" and "Required" is handled exactly as marked by the organizer.

**Comment by SaptakS** [comment]
Closing this issue. Follow up for showing comments only to organizers only https://github.com/fossasia/open-event-orga-server/issues/1086
