### ISSUE TITLE
Implement Simple Signup for Not logged in users, who are signing up for events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#639]
Think of a potential speaker, who answers the call for papers. Flow is as follows
1. Potential speaker receives a link to the call for papers, goes to the call for papers page and clicks on "submit session" button.
2. Without logging in the potential speaker (as anonymous user) should be able to 
- [x] fill out form "sessions" 
- [x] be prompted for email and password to sign up or sign in if he/she clicks "save draft"
- [x] Result: If speakers enters email address, he/she will receive a confirmation mail with the requirement to confirm the email. This is just like a sign up.

**Comment by SaptakS** [comment]
@mariobehling I am working on it.

**Comment by mariobehling** [comment]
There is a related issue and discussion about email and signup process here as well: https://github.com/fossasia/open-event-orga-server/issues/965

**Comment by SaptakS** [comment]
@mariobehling , @niranjan94 said he would be working on it. If he doesn't, I will take it up.

**Comment by SaptakS** [comment]
@mariobehling as said in #965 we will be having only a single form instead of a wizard. So I think this issue then only will require the last point. Right?

**Comment by SaptakS** [comment]
@mariobehling This is the implementation that I have created: -
* The user is not logged in and creates a session. If he is not already registered, we register him, assign role as speaker and send an email with a randomly generated password
![screenshot from 2016-06-19 17 28 26](https://cloud.githubusercontent.com/assets/9530293/16177172/866b5584-3643-11e6-99fb-585a27f7c335.png)
* He can then verify is registration and login.

**Comment by SaptakS** [comment]
Also, I am not sure what to do if the speaker is already registered but is not logged in while filling up form.

**Comment by mariobehling** [comment]
@SaptakS Login questions are outlined here: https://github.com/fossasia/open-event-orga-server/issues/965 already.

**Comment by SaptakS** [comment]
@mariobehling I think this [PR](https://github.com/fossasia/open-event-orga-server/pull/1041) already solves the purpose. Because as far as I understand, a non registered speaker would fill up session form only from `/e/ID/cfs` page. And to fill form from `/event/ID/sessions/create` ,  I think he needs to be logged in. What do you think @niranjan94 ?

**Comment by mariobehling** [comment]
Sounds good. Please give me a sample set up and link to test it.

**Comment by niranjan94** [comment]
http://open-event.herokuapp.com/e/3/cfs/

**Comment by mariobehling** [comment]
Internal Server Error when saving as draft or submitting.

**Comment by niranjan94** [comment]
@mariobehling working on

**Comment by niranjan94** [comment]
@mariobehling fixed.

**Comment by mariobehling** [comment]
Test show, if I submit as draft or session - both shows up as "submitted".

![screenshot from 2016-06-20 12 29 38](https://cloud.githubusercontent.com/assets/1583873/16191080/cf5f36da-36e2-11e6-9eee-19a360d487d4.png)

If I edit proposal I get to another form, not the original form. Why?

![screenshot from 2016-06-20 12 31 33](https://cloud.githubusercontent.com/assets/1583873/16191125/047e0a30-36e3-11e6-9793-9efd3ee49196.png)

**Comment by niranjan94** [comment]
@mariobehling I'll fix that ... As for the form, I made the My Sessions part before the session form was implemented. I'll change that too.
