### ISSUE TITLE
Uploading files 

### ISSUE THREAD

**Issue by rafalkowalski** [fossasia/open-event-orga-server#740]
we need a function which allows us to upload image(images)

Used on Pages:
- [x] Create Event Wizard Step 2: Sponsors #697 
- [x] Create Organizer Profile Page #688 
- [x] Session Create Wizard e.g. upload slides https://github.com/fossasia/open-event-orga-server/issues/631

**Comment by rafalkowalski** [comment]
#697 #688

**Comment by aditya1702** [comment]
@rafalkowalski I will do this

**Comment by rafalkowalski** [comment]
cool @aditya1702 talk with @SaptakS if he's working on it

**Comment by aditya1702** [comment]
@rafalkowalski the image can be uploaded to a folder. But then do we need to display the image in the sponsors table?

**Comment by rafalkowalski** [comment]
of course that image should be store in a folder. In user and sponsor table i think that we need to store an  path to this image? what do you think? @SaptakS @aditya1702 @niranjan94

**Comment by niranjan94** [comment]
Yep. The table can have the path to the image.

**Comment by niranjan94** [comment]
Or we could generate the full URL to the image and store in the DB. This way, we can give the organizer to either upload image or just give the URL to an existing image. If they prefer URL, less storage space usage for us. :)

**Comment by SaptakS** [comment]
@niranjan94 I think thats a great idea.. That way, we will just have to put the DB content for URL in img src. It will be a more generic approach.

**Comment by aditya1702** [comment]
@SaptakS @niranjan94 I too agree.

**Comment by rafalkowalski** [comment]
@aditya1702 how is it?

**Comment by mariobehling** [comment]
@SaptakS @niranjan94 @rafalkowalski @aditya1702 Regarding uploading files, we also need to upload audio and video potentially and here it might be more viable to keep it hosted externally or eg. on Amazon S3. Regarding image files, yes possibly we can host images externally as well, but if image links are changing this could be a problem. So best is if we could upload images either directly or if people give us a URL link, we could grab images from a link.

**Comment by aditya1702** [comment]
@SaptakS @niranjan94 @rafalkowalski Are we going to have a separate 'Add Image' button and form or are we directly allowing upload from the table like this:
![logo](https://cloud.githubusercontent.com/assets/15054664/16032927/ac785040-3226-11e6-9e2b-f425ab892d94.png)

**Comment by niranjan94** [comment]
@aditya1702 I think direct from the table would be suitable

**Comment by rafalkowalski** [comment]
@aditya1702 do you need help with upload files?

**Comment by aditya1702** [comment]
@rafalkowalski I am almost finished :) . Will make a pull in a few mins. I closed the request because it had a lot of merge conflicts :sweat_smile:
