### ISSUE TITLE
Anonymous User: See event and Schedule

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#782]
As outlined in #622 .

Url: `/e/ID/` - the public page that holds the main information of an event (Maing menu with all event links, Tag Line, Event Description, Date, Time, Newsletter, Contact, Social Media, Twitter Timeline Embed, Location with Map)

- [x] `/e/ID/` - the public page that holds the main information of an event (#784)
- [x] `/e/ID/#speakers` - the section on the event page that shows all accepted speakers of an event (#784)
- [x] `/e/ID/#sponsors` - the section on the event page that shows all sponsors and partners of an event (#784)
- [x] `/e/ID/#organizers` - the section on the event page page that shows all organizers of an event (#784)
- [x] `/e/ID/cfs` - the public page that holds the Call for Speakers (with a register button)
- [x] `/e/ID/session` - the section on the event page page that shows all sessions of an event (#960)
- [ ] `/e/ID/coc` - the public page that shows a code of conduct if available
- [x] `/e/ID/schedule` - the public page where everyone can see the schedule of an event. (#1009)

**Comment by niranjan94** [comment]
**Sample page from Eventbrite:**
![screencapture-www-eventbrite-com-e-lorem-ipsum-dolor-tickets-26035166885-1465830447016](https://cloud.githubusercontent.com/assets/2404372/16012354/b4b64864-31a6-11e6-922c-b346779864bc.png)

**Comment by niranjan94** [comment]
@mariobehling which all parts of this would be coming from the webapp generator ?

**Comment by niranjan94** [comment]
@mariobehling which all parts of this would be coming from the webapp generator ?

**Comment by mariobehling** [comment]
The web app generator is unrelated to this. We will use the app generator mainly for external sites.

**Comment by mariobehling** [comment]
we might change the view on this. Maybe we will use the same design. At the moment the first step is to make the pages work.

**Comment by niranjan94** [comment]
@mariobehling Okay ... I'll get this ready then.

**Comment by mariobehling** [comment]
Please add a button "View" to the specific event dashboard as well. So organizers can find this event.
