### ISSUE TITLE
Create APIs, make sample JSON files and document it

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#799]
To start off we can use the APIs of the OpenTechSummit https://github.com/fossasia/open-event-orga-server/issues/624 and https://github.com/OpenTechSummit/2016.opentechsummit.net/tree/gh-pages/programm/json

Please add all APIs and relevant issues in the list below:
* [x] Event API https://github.com/fossasia/open-event-orga-server/issues/612
* [x] Speakers API https://github.com/fossasia/open-event-orga-server/issues/618
* [x] Profile API https://github.com/fossasia/open-event-orga-server/issues/617
* [x] Sponsors API https://github.com/fossasia/open-event-orga-server/issues/615
* [x] Track API https://github.com/fossasia/open-event-orga-server/issues/614
* [x] Microlocation API https://github.com/fossasia/open-event-orga-server/issues/616
* [x] Sessions API https://github.com/fossasia/open-event-orga-server/issues/613

**Comment by mariobehling** [comment]
Currently, I see a "Format" API and a "Levels" API. I don't know what it is and I don't think we need it.

**Comment by shivamMg** [comment]
@mariobehling I'm removing the Format API and Level API. And, the format field and level field from Sessions (both database models and apis). None of us really know what they actually are.
