### ISSUE TITLE
Create main tab in Admin Area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#863]
1. Create a heading "Administration"

2. Create a top menu similar to the one below (manage events) with the links to the following:
     * [x] Events -> `/admin/events/` https://github.com/fossasia/open-event-orga-server/issues/871
     * [x] Sessions -> `/admin/sessions/` #870
     * [x] Users -> `/admin/users/` https://github.com/fossasia/open-event-orga-server/issues/853
     * [x] Permissions -> `/admin/permissions/` https://github.com/fossasia/open-event-orga-server/issues/854
     * [x] Reports -> `/admin/reports/` https://github.com/fossasia/open-event-orga-server/issues/872

![screenshot from 2016-06-15 18 10 44](https://cloud.githubusercontent.com/assets/1583873/16087915/2045a87a-3325-11e6-82a4-c4c1df73ed1b.png)

**Comment by mariobehling** [comment]
Actually this was not completely thought through. We need the white tab area for the menus of each point.

What other options do we have? Maybe sth. like the below?

![screenshot from 2016-06-16 18 49 31](https://cloud.githubusercontent.com/assets/1583873/16125422/dc118938-33f3-11e6-8b6f-4582fe5a4557.png)

**Comment by rafalkowalski** [comment]
it looks nice but maybe simple menu will be enough?

**Comment by mariobehling** [comment]
It is not so much about the style. It is about using the space. Just use whatever styles are available in Genetella. I just want to keep the white area available for the data and subtabs. As an inspiration below.

![screenshot from 2016-06-16 18 49 31](https://cloud.githubusercontent.com/assets/1583873/16126312/d69bb6b4-33f7-11e6-8ebc-51023e121221.png)

**Comment by SaptakS** [comment]
@mariobehling this can be done.. We can shift it to right like in your design to use more space..

**Comment by SaptakS** [comment]
@mariobehling can this issue be closed?
