### ISSUE TITLE
Improve Sessions Process and Implementation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#965]
There are issues with the sessions implementation and improvement necessary to ensure the flow of the user. Please implement the following:

**My Sessions**
* [x] Ensure the user sessions show up at `/events/mysessions/`

**Form** #990
* [x] For a given event show **all specified fields** in the session proposal form of speakers (e.g. https://open-event.herokuapp.com/events/50/sessions/create/). -> The session fields are specified in the create event wizard in step 5.
* [x] Make "Create Session" into one page form (instead of a wizard) 
* [x] Implement button "Save Draft" and "Submit" on bottom of create sessions form.

**Email and Login** https://github.com/fossasia/open-event-orga-server/issues/1030
* [x] If user is logged in prefill in field "Email" with system email (and make it non-changeable). Add a message: "You can change this email in your profile settings."
* [x] Show "Drafts" in the list of sessions for an event of organizers, but do not send an email to them.
* [x] Send an email to organizer when a user "Submitted" a form with a link to view the session.
* [x] Add button "Submit Proposal" to page "Call for Speakers" (`/e/ID/cfs/`) and open form as Lightbox. 
   * [x] If user was not logged in: After that follow and ensure flow for sign up as defined in https://github.com/fossasia/open-event-orga-server/issues/639
   * [x] If user was logged in he/she needs to have the email prefilled in as mentioned above.
   * [x] If user is not logged in, but wants to use an email address that is registered already, prompt the speaker to login to use that email address or use another email.

**Comment by SaptakS** [comment]
@mariobehling when you say to make it into a single form rather than a wizard, do you mean that both session and speaker details should be there in a single page? Wouldn't that look too clumsy?

**Comment by mariobehling** [comment]
Yes, please do. Everything in one page. Thanks.

**Comment by SaptakS** [comment]
@mariobehling is this ok?
![session_form](https://cloud.githubusercontent.com/assets/9530293/16171554/4af4387c-358f-11e6-9dfb-6e6029074bf2.png)

**Comment by mariobehling** [comment]
I think this issue is too big for all details. Please create sub-issues for each area. Relate here to form issues, please: https://github.com/fossasia/open-event-orga-server/issues/990
